name: CI on push pull_request

on:
  push:
    branches:
      [ master ]
  pull_request:
    branches:
      [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: run eslint
        run: npm run lint:ts
      - name: run stylelint
        run: npm run stylelint:scss
      - name: run unit tests
        run: npm run test:unit

